'use strict';

const fs = require('node:fs');
const path = require('node:path');

const GENERATED_HEADER = [
  '<!-- GENERATED BY jarvos-secondbrain-wiki. DO NOT EDIT.',
  'Source notes, journals, and .jarvos/knowledge sidecars are authoritative.',
  '-->',
  '',
].join('\n');

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function slugify(value) {
  const slug = String(value || '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 96);
  return slug || 'item';
}

function markdownEscape(value) {
  return String(value || '').replace(/\|/g, '\\|').trim();
}

function readArtifacts(artifactsDir) {
  if (!fs.existsSync(artifactsDir)) return [];
  return fs.readdirSync(artifactsDir)
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map((name) => {
      const artifactPath = path.join(artifactsDir, name);
      return {
        artifactPath,
        artifact: readJson(artifactPath),
      };
    })
    .filter(({ artifact }) => isWikiEligibleArtifact(artifact))
    .map(({ artifactPath, artifact }) => ({
      artifactPath,
      artifact: {
        ...artifact,
        knowledgeUnits: (artifact.knowledgeUnits || []).filter(isWikiEligibleKnowledgeUnit),
      },
    }));
}

function isPrivateTier(tier) {
  return ['private', 'sensitive', 'secret'].includes(String(tier || '').toLowerCase());
}

function isWikiEligibleKnowledgeUnit(unit = {}) {
  if (unit.downstreamEligibility?.memoryWiki === false) return false;
  if (unit.privacyDecision?.excludedFromPromotion) return false;
  if (isPrivateTier(unit.privacyDecision?.tier)) return false;
  return true;
}

function isWikiEligibleArtifact(artifact = {}) {
  if (artifact.sensitivity?.excluded) return false;
  if (isPrivateTier(artifact.privacyTier)) return false;
  return (artifact.knowledgeUnits || []).some(isWikiEligibleKnowledgeUnit);
}

function conceptsForArtifact(artifact) {
  const concepts = new Set(artifact.concepts || []);
  for (const unit of artifact.knowledgeUnits || []) {
    concepts.add(slugify(unit.title));
    for (const word of String(unit.text || '').match(/\b[A-Z][A-Za-z0-9]+(?:\s+[A-Z][A-Za-z0-9]+){0,3}\b/g) || []) {
      concepts.add(slugify(word));
    }
  }
  return [...concepts].filter(Boolean).sort();
}

function groupByConcept(artifactEntries) {
  const grouped = new Map();
  for (const entry of artifactEntries) {
    for (const concept of conceptsForArtifact(entry.artifact)) {
      if (!grouped.has(concept)) grouped.set(concept, []);
      grouped.get(concept).push(entry);
    }
  }
  return [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function journalDate(artifact) {
  const backlink = artifact.provenance?.journalBacklink;
  if (!backlink || typeof backlink !== 'object') return null;
  const journalPath = String(backlink.journalPath || backlink.path || '');
  const match = journalPath.match(/(\d{4}-\d{2}-\d{2})/);
  return match ? match[1] : null;
}

function sourceLink(artifact) {
  return artifact.provenance?.citation || `[[${artifact.title || artifact.sourceNote}]]`;
}

function renderKnowledgeUnit(unit, artifact) {
  return [
    `- ${markdownEscape(unit.text)}`,
    `  - Source: ${sourceLink(artifact)}`,
    `  - Evidence: ${markdownEscape(unit.evidence?.[0]?.quote || unit.text)}`,
    `  - Privacy: ${unit.privacyDecision?.tier || artifact.privacyTier || 'unknown'}`,
  ].join('\n');
}

function renderConceptPage(concept, entries) {
  const lines = [
    GENERATED_HEADER,
    `# ${concept}`,
    '',
    '## Knowledge Units',
    '',
  ];

  for (const { artifact } of entries) {
    const units = (artifact.knowledgeUnits || []).filter((unit) => {
      const haystack = `${unit.title || ''}\n${unit.text || ''}`.toLowerCase();
      return haystack.includes(concept.replace(/-/g, ' ')) || (artifact.concepts || []).includes(concept);
    });
    for (const unit of units.length ? units : artifact.knowledgeUnits || []) {
      lines.push(renderKnowledgeUnit(unit, artifact), '');
    }
  }

  lines.push('## Sources', '');
  for (const { artifact } of entries) {
    lines.push(`- ${sourceLink(artifact)} - ${markdownEscape(artifact.sourceNote)}`);
  }

  return `${lines.join('\n').trim()}\n`;
}

function renderSourcePage(artifact) {
  const lines = [
    GENERATED_HEADER,
    `# ${artifact.title || artifact.sourceNote}`,
    '',
    `Source note: ${markdownEscape(artifact.sourceNote)}`,
    `Citation: ${sourceLink(artifact)}`,
    `Privacy: ${artifact.privacyTier || 'unknown'}`,
    '',
    '## Summary',
    '',
    markdownEscape(artifact.summary || ''),
    '',
    '## Knowledge Units',
    '',
  ];

  for (const unit of artifact.knowledgeUnits || []) {
    lines.push(renderKnowledgeUnit(unit, artifact), '');
  }

  return `${lines.join('\n').trim()}\n`;
}

function renderDailyPage(date, entries) {
  const lines = [
    GENERATED_HEADER,
    `# ${date}`,
    '',
    '## Sources',
    '',
  ];

  for (const { artifact } of entries) {
    lines.push(`- ${sourceLink(artifact)} - ${markdownEscape(artifact.summary || artifact.sourceNote)}`);
  }

  return `${lines.join('\n').trim()}\n`;
}

function renderRootIndex({ conceptPages, sourcePages, dailyPages }) {
  const lines = [
    GENERATED_HEADER,
    '# JarvOS Generated Secondbrain Wiki',
    '',
    'This wiki is rebuildable from source notes, journals, and sidecar artifacts.',
    '',
    '## Concepts',
    '',
    ...conceptPages.map((page) => `- [${page.title}](${page.path})`),
    '',
    '## Sources',
    '',
    ...sourcePages.map((page) => `- [${page.title}](${page.path})`),
    '',
    '## Daily',
    '',
    ...dailyPages.map((page) => `- [${page.title}](${page.path})`),
  ];

  return `${lines.join('\n').trim()}\n`;
}

function writeGeneratedFile(outputDir, relativePath, content) {
  const filePath = path.join(outputDir, relativePath);
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
  return filePath;
}

function resetGeneratedOutput(outputDir) {
  for (const entry of ['concepts', 'sources', 'daily', 'index.md']) {
    fs.rmSync(path.join(outputDir, entry), { recursive: true, force: true });
  }
}

function compileSecondbrainWiki({ artifactsDir, outputDir }) {
  if (!artifactsDir) throw new Error('artifactsDir is required');
  if (!outputDir) throw new Error('outputDir is required');

  const entries = readArtifacts(artifactsDir);
  ensureDir(outputDir);
  resetGeneratedOutput(outputDir);

  const conceptPages = [];
  for (const [concept, conceptEntries] of groupByConcept(entries)) {
    const relativePath = `concepts/${concept}.md`;
    writeGeneratedFile(outputDir, relativePath, renderConceptPage(concept, conceptEntries));
    conceptPages.push({ title: concept, path: relativePath });
  }

  const sourcePages = [];
  for (const { artifact } of entries) {
    const title = artifact.title || artifact.sourceNote || 'source';
    const relativePath = `sources/${slugify(title)}.md`;
    writeGeneratedFile(outputDir, relativePath, renderSourcePage(artifact));
    sourcePages.push({ title, path: relativePath });
  }

  const dailyGroups = new Map();
  for (const entry of entries) {
    const date = journalDate(entry.artifact);
    if (!date) continue;
    if (!dailyGroups.has(date)) dailyGroups.set(date, []);
    dailyGroups.get(date).push(entry);
  }

  const dailyPages = [];
  for (const [date, dailyEntries] of [...dailyGroups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const relativePath = `daily/${date}.md`;
    writeGeneratedFile(outputDir, relativePath, renderDailyPage(date, dailyEntries));
    dailyPages.push({ title: date, path: relativePath });
  }

  writeGeneratedFile(outputDir, 'index.md', renderRootIndex({ conceptPages, sourcePages, dailyPages }));

  return {
    artifacts: entries.length,
    conceptPages: conceptPages.length,
    sourcePages: sourcePages.length,
    dailyPages: dailyPages.length,
    outputDir,
  };
}

module.exports = {
  GENERATED_HEADER,
  compileSecondbrainWiki,
  renderConceptPage,
  renderSourcePage,
  renderRootIndex,
  slugify,
};
