'use strict';

const {
  releaseFitFromPaperclipReleaseIntake,
} = require('./adapters/paperclip');
const {
  DEFAULT_MCP_TOOL_NAME,
  DEFAULT_SKILL_NAME,
  HOST_ADAPTER_SCHEMA_VERSION,
  SUPPORTED_HOSTS,
  buildMcpToolDescriptor,
  buildSkillDescriptor,
  codingHostAdapterContract,
  createClaudeCodeHostAdapter,
  createCodexHostAdapter,
  createCodingHostAdapter,
  normalizeHost,
} = require('./adapters/hosts');
const {
  classifyProductFit,
  classifyReadiness,
  classifyReleaseFit,
  decideCodingTriage,
  mergeConfig,
  routeCodingWork,
  triageCodingWork,
} = require('./features/triage');
const {
  normalizeLabels,
} = require('./core/text');
const {
  RUNTIME_CHECKOUT_PREFLIGHT_SCHEMA_VERSION,
  classifyRuntimeCheckoutRole,
  inspectRuntimeCheckout,
  runtimeCheckoutPreflight,
} = require('./features/runtime-checkout-preflight');
const {
  REQUIRED_EVIDENCE,
  branchSatisfiesIdentifier,
  buildSubmissionGate,
  formatSubmissionGateMarkdown,
  issueSatisfiesIdentifier,
  validateSubmissionEvidence,
} = require('./features/submission-gate');
const {
  ORCHESTRATOR_SCHEMA_VERSION,
  TAKE_ISSUE_TO_DONE_STAGES,
  runTakeIssueToDone,
} = require('./features/orchestrator');
const {
  REVIEW_ENGINE_SCHEMA_VERSION,
  assertReviewEngineAdapter,
  createClawpatchAutoreviewAdapter,
} = require('./features/review-engine');
const {
  CODE_THREAD_KIND,
  ARTICLE_THREAD_KIND,
  SESSION_STATE_SCHEMA_VERSION,
  buildSessionCheckpoint,
  buildArticleThreadCheckpoint,
  buildCodeThreadCheckpoint,
  buildLiveArtifactPointer,
  createFileSessionStateStore,
  createMemorySessionStateStore,
  readJarvosSessionState,
  writeJarvosSessionState,
} = require('./features/session-state');
const {
  CODING_MATURITY_STATES,
  SUBMISSION_GATE_PHASES,
  SUBMISSION_GATE_SCHEMA_VERSION,
  SUBMISSION_GATE_STAGES,
  TRIAGE_SCHEMA_VERSION,
  codingLifecyclePolicy,
  evaluateSubmissionGate,
  releaseGateState,
  submissionGateContract,
} = require('./lifecycle/policy');
const {
  ACTIVE_STATUSES,
  TERMINAL_STATUSES,
  buildDecision,
  classifyCheckoutKind,
  classifyWorktreeOwnership,
  evaluateBranchHygiene,
  extractIssueIdentifier,
  getCurrentBranch,
  inspectRepository,
  parseGitStatus,
} = require('./worktree-ownership');

module.exports = {
  ACTIVE_STATUSES,
  CODING_MATURITY_STATES,
  CODE_THREAD_KIND,
  ARTICLE_THREAD_KIND,
  DEFAULT_MCP_TOOL_NAME,
  DEFAULT_SKILL_NAME,
  HOST_ADAPTER_SCHEMA_VERSION,
  ORCHESTRATOR_SCHEMA_VERSION,
  REQUIRED_EVIDENCE,
  REVIEW_ENGINE_SCHEMA_VERSION,
  SESSION_STATE_SCHEMA_VERSION,
  SUBMISSION_GATE_PHASES,
  SUBMISSION_GATE_SCHEMA_VERSION,
  SUBMISSION_GATE_STAGES,
  SUPPORTED_HOSTS,
  TAKE_ISSUE_TO_DONE_STAGES,
  TERMINAL_STATUSES,
  TRIAGE_SCHEMA_VERSION,
  assertReviewEngineAdapter,
  buildDecision,
  buildCodeThreadCheckpoint,
  buildMcpToolDescriptor,
  buildSessionCheckpoint,
  buildArticleThreadCheckpoint,
  buildLiveArtifactPointer,
  buildSkillDescriptor,
  createFileSessionStateStore,
  branchSatisfiesIdentifier,
  buildSubmissionGate,
  classifyCheckoutKind,
  classifyProductFit,
  classifyReadiness,
  classifyReleaseFit,
  classifyRuntimeCheckoutRole,
  classifyWorktreeOwnership,
  codingLifecyclePolicy,
  codingHostAdapterContract,
  createClaudeCodeHostAdapter,
  createClawpatchAutoreviewAdapter,
  createCodexHostAdapter,
  createCodingHostAdapter,
  createMemorySessionStateStore,
  decideCodingTriage,
  evaluateSubmissionGate,
  evaluateBranchHygiene,
  extractIssueIdentifier,
  formatSubmissionGateMarkdown,
  getCurrentBranch,
  inspectRuntimeCheckout,
  inspectRepository,
  issueSatisfiesIdentifier,
  mergeConfig,
  normalizeHost,
  normalizeLabels,
  parseGitStatus,
  readJarvosSessionState,
  releaseFitFromPaperclipReleaseIntake,
  releaseGateState,
  RUNTIME_CHECKOUT_PREFLIGHT_SCHEMA_VERSION,
  runtimeCheckoutPreflight,
  runTakeIssueToDone,
  submissionGateContract,
  routeCodingWork,
  triageCodingWork,
  validateSubmissionEvidence,
  writeJarvosSessionState,
};
