'use strict';

const {
  releaseFitFromPaperclipReleaseIntake,
} = require('./adapters/paperclip');
const {
  BRANCH_SCHEMA_VERSION,
  COUPLED_STAGES,
  FIXER_SCHEMA_VERSION,
  HOLISTIC_REVIEW_SCHEMA_VERSION,
  LIVE_ADAPTERS_SCHEMA_VERSION,
  PULL_REQUEST_SCHEMA_VERSION,
  POST_MERGE_SCHEMA_VERSION,
  TRACKER_SCHEMA_VERSION,
  buildLiveCodingAdapters,
  createLiveClawpatchReviewEngine,
  createLiveClawpatchRunner,
  createLiveGitBranch,
  createLiveHolisticReview,
  createLiveFixer,
  createLivePaperclipTracker,
  createLivePostMergeSweep,
  createLivePullRequest,
  parseClawpatchCommand,
  resolveWorktreeRoot,
} = require('./adapters/live');
const {
  DEFAULT_MCP_TOOL_NAME,
  DEFAULT_SKILL_NAME,
  HOST_ADAPTER_SCHEMA_VERSION,
  SUPPORTED_HOSTS,
  buildMcpToolDescriptor,
  buildSkillDescriptor,
  codingHostAdapterContract,
  continuityAdapterMatrix,
  createClaudeCodeHostAdapter,
  createCodexHostAdapter,
  createCodingHostAdapter,
  normalizeHost,
} = require('./adapters/hosts');
const {
  classifyProductFit,
  classifyReadiness,
  classifyReleaseFit,
  decideCodingTriage,
  mergeConfig,
  routeCodingWork,
  triageCodingWork,
} = require('./features/triage');
const {
  normalizeLabels,
} = require('./core/text');
const {
  RUNTIME_CHECKOUT_PREFLIGHT_SCHEMA_VERSION,
  classifyRuntimeCheckoutRole,
  inspectRuntimeCheckout,
  runtimeCheckoutPreflight,
} = require('./features/runtime-checkout-preflight');
const {
  REQUIRED_EVIDENCE,
  branchSatisfiesIdentifier,
  buildSubmissionGate,
  formatSubmissionGateMarkdown,
  issueSatisfiesIdentifier,
  validateSubmissionEvidence,
} = require('./features/submission-gate');
const {
  ORCHESTRATOR_SCHEMA_VERSION,
  TAKE_ISSUE_TO_DONE_STAGES,
  runTakeIssueToDone,
} = require('./features/orchestrator');
const {
  GATE_EQUIVALENT_PROFILES,
  GATE_EQUIVALENT_SURFACES,
  REVIEW_ENGINE_SCHEMA_VERSION,
  assertReviewEngineAdapter,
  buildGateEquivalentCommands,
  createCommandReviewEngine,
  createClawpatchAutoreviewAdapter,
  createGateEquivalentReviewEngine,
  getGateEquivalentProfile,
  interpolateCommand,
} = require('./features/review-engine');
const {
  GOAL_ALIGNMENT_SCHEMA_VERSION,
  buildGoalClarityEscalation,
  buildGoalClarityQuestion,
  evaluateGoalAlignment,
  findPendingGoalClarityInteraction,
  isGoalClarityInteraction,
  normalizeGoalAlignmentReview,
} = require('./features/goal-alignment');
const {
  CODE_THREAD_KIND,
  ARTICLE_THREAD_KIND,
  SESSION_STATE_SCHEMA_VERSION,
  buildSessionCheckpoint,
  buildArticleThreadCheckpoint,
  buildCodeThreadCheckpoint,
  buildLiveArtifactPointer,
  createFileSessionStateStore,
  createMemorySessionStateStore,
  readJarvosSessionState,
  writeJarvosSessionState,
} = require('./features/session-state');
const {
  CODING_MATURITY_STATES,
  ISSUE_BRANCH_LIFECYCLE_SCHEMA_VERSION,
  ISSUE_BRANCH_LIFECYCLE_STATES,
  ISSUE_BRANCH_LIFECYCLE_TRANSITIONS,
  ISSUE_BRANCH_METADATA_REQUIREMENTS,
  SUBMISSION_GATE_PHASES,
  SUBMISSION_GATE_SCHEMA_VERSION,
  SUBMISSION_GATE_STAGES,
  TRIAGE_SCHEMA_VERSION,
  codingLifecyclePolicy,
  evaluateIssueBranchLifecycle,
  evaluateSubmissionGate,
  issueBranchLifecycleContract,
  releaseGateState,
  submissionGateContract,
} = require('./lifecycle/policy');
const {
  ACTIVE_STATUSES,
  TERMINAL_STATUSES,
  buildDecision,
  classifyCheckoutKind,
  classifyWorktreeOwnership,
  evaluateBranchHygiene,
  extractIssueIdentifier,
  getCurrentBranch,
  inspectRepository,
  parseGitStatus,
} = require('./worktree-ownership');

module.exports = {
  ACTIVE_STATUSES,
  BRANCH_SCHEMA_VERSION,
  COUPLED_STAGES,
  FIXER_SCHEMA_VERSION,
  HOLISTIC_REVIEW_SCHEMA_VERSION,
  LIVE_ADAPTERS_SCHEMA_VERSION,
  PULL_REQUEST_SCHEMA_VERSION,
  POST_MERGE_SCHEMA_VERSION,
  TRACKER_SCHEMA_VERSION,
  buildLiveCodingAdapters,
  createLiveClawpatchReviewEngine,
  createLiveClawpatchRunner,
  createLiveGitBranch,
  createLiveHolisticReview,
  createLiveFixer,
  createLivePaperclipTracker,
  createLivePostMergeSweep,
  createLivePullRequest,
  parseClawpatchCommand,
  resolveWorktreeRoot,
  CODING_MATURITY_STATES,
  CODE_THREAD_KIND,
  ARTICLE_THREAD_KIND,
  DEFAULT_MCP_TOOL_NAME,
  DEFAULT_SKILL_NAME,
  GATE_EQUIVALENT_PROFILES,
  GATE_EQUIVALENT_SURFACES,
  GOAL_ALIGNMENT_SCHEMA_VERSION,
  HOST_ADAPTER_SCHEMA_VERSION,
  ISSUE_BRANCH_LIFECYCLE_SCHEMA_VERSION,
  ISSUE_BRANCH_LIFECYCLE_STATES,
  ISSUE_BRANCH_LIFECYCLE_TRANSITIONS,
  ISSUE_BRANCH_METADATA_REQUIREMENTS,
  ORCHESTRATOR_SCHEMA_VERSION,
  REQUIRED_EVIDENCE,
  REVIEW_ENGINE_SCHEMA_VERSION,
  SESSION_STATE_SCHEMA_VERSION,
  SUBMISSION_GATE_PHASES,
  SUBMISSION_GATE_SCHEMA_VERSION,
  SUBMISSION_GATE_STAGES,
  SUPPORTED_HOSTS,
  TAKE_ISSUE_TO_DONE_STAGES,
  TERMINAL_STATUSES,
  TRIAGE_SCHEMA_VERSION,
  assertReviewEngineAdapter,
  buildGateEquivalentCommands,
  buildDecision,
  buildCodeThreadCheckpoint,
  buildMcpToolDescriptor,
  buildSkillDescriptor,
  buildGoalClarityEscalation,
  buildGoalClarityQuestion,
  buildSessionCheckpoint,
  buildArticleThreadCheckpoint,
  buildLiveArtifactPointer,
  createFileSessionStateStore,
  branchSatisfiesIdentifier,
  buildSubmissionGate,
  classifyCheckoutKind,
  classifyProductFit,
  classifyReadiness,
  classifyReleaseFit,
  classifyRuntimeCheckoutRole,
  classifyWorktreeOwnership,
  codingLifecyclePolicy,
  codingHostAdapterContract,
  continuityAdapterMatrix,
  createClaudeCodeHostAdapter,
  createCommandReviewEngine,
  createClawpatchAutoreviewAdapter,
  createCodexHostAdapter,
  createCodingHostAdapter,
  createGateEquivalentReviewEngine,
  createMemorySessionStateStore,
  decideCodingTriage,
  evaluateIssueBranchLifecycle,
  evaluateGoalAlignment,
  evaluateSubmissionGate,
  evaluateBranchHygiene,
  extractIssueIdentifier,
  findPendingGoalClarityInteraction,
  formatSubmissionGateMarkdown,
  getGateEquivalentProfile,
  getCurrentBranch,
  inspectRuntimeCheckout,
  inspectRepository,
  interpolateCommand,
  issueBranchLifecycleContract,
  issueSatisfiesIdentifier,
  isGoalClarityInteraction,
  mergeConfig,
  normalizeGoalAlignmentReview,
  normalizeHost,
  normalizeLabels,
  parseGitStatus,
  readJarvosSessionState,
  releaseFitFromPaperclipReleaseIntake,
  releaseGateState,
  RUNTIME_CHECKOUT_PREFLIGHT_SCHEMA_VERSION,
  runtimeCheckoutPreflight,
  runTakeIssueToDone,
  submissionGateContract,
  routeCodingWork,
  triageCodingWork,
  validateSubmissionEvidence,
  writeJarvosSessionState,
};
