'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const {
  compileSecondbrainWiki,
  DEFAULT_WIKI_DIR_NAME,
  MANAGED_OUTPUT_MARKER,
  resolveWikiBuildOptions,
} = require('../packages/jarvos-secondbrain-wiki/src');
const {
  buildArtifact,
} = require('../packages/jarvos-secondbrain-notes/src/knowledge-optimizer');

function fixtureRoot() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'jarvos-wiki-'));
  const notesDir = path.join(root, 'Notes');
  const artifactsDir = path.join(root, '.jarvos', 'knowledge', 'artifacts');
  const outputDir = path.join(root, 'Generated Wiki');
  fs.mkdirSync(notesDir, { recursive: true });
  fs.mkdirSync(artifactsDir, { recursive: true });
  return { root, notesDir, artifactsDir, outputDir };
}

function writeArtifact({ notesDir, artifactsDir, title, body, journalPath = null }) {
  const notePath = path.join(notesDir, `${title}.md`);
  fs.writeFileSync(notePath, body, 'utf8');
  const artifact = buildArtifact({
    filePath: notePath,
    notesDir,
    title,
    body,
    frontmatter: {
      author: 'andrew',
      type: 'reference',
    },
    created: true,
    journal: journalPath ? { journalPath } : null,
  });
  const artifactPath = path.join(artifactsDir, `${title.toLowerCase().replace(/\s+/g, '-')}.json`);
  fs.writeFileSync(artifactPath, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');
  return { notePath, artifactPath, artifact };
}

test('compileSecondbrainWiki builds deterministic concept source daily and index pages', () => {
  const { root, notesDir, artifactsDir, outputDir } = fixtureRoot();
  writeArtifact({
    notesDir,
    artifactsDir,
    title: 'Generated Wiki',
    body: [
      '# Generated Wiki',
      '',
      'Generated wiki pages are rebuildable from source notes and journals.',
      'Memory promotion should only accept cited knowledge units.',
    ].join('\n'),
    journalPath: path.join(root, 'Journal', '2026-06-21.md'),
  });

  const first = compileSecondbrainWiki({ artifactsDir, outputDir });
  const firstIndex = fs.readFileSync(path.join(outputDir, 'index.md'), 'utf8');
  const firstConcept = fs.readFileSync(path.join(outputDir, 'concepts', 'generated-wiki.md'), 'utf8');

  const second = compileSecondbrainWiki({ artifactsDir, outputDir });
  const secondIndex = fs.readFileSync(path.join(outputDir, 'index.md'), 'utf8');
  const secondConcept = fs.readFileSync(path.join(outputDir, 'concepts', 'generated-wiki.md'), 'utf8');

  assert.deepEqual(first, second);
  assert.equal(first.artifacts, 1);
  assert.equal(first.sourcePages, 1);
  assert.ok(first.conceptPages >= 1);
  assert.equal(first.dailyPages, 1);
  assert.equal(firstIndex, secondIndex);
  assert.equal(firstConcept, secondConcept);
  assert.match(firstIndex, /GENERATED BY jarvos-secondbrain-wiki/);
  assert.match(firstIndex, /concepts\/generated-wiki\.md/);
  assert.match(firstConcept, /\[\[Generated Wiki\]\]/);
  assert.match(firstConcept, /Source: \[\[Generated Wiki\]\]/);
  assert.ok(fs.existsSync(path.join(outputDir, 'daily', '2026-06-21.md')));
  assert.ok(fs.existsSync(path.join(outputDir, MANAGED_OUTPUT_MARKER)));
});

test('compileSecondbrainWiki does not mutate source notes', () => {
  const { notesDir, artifactsDir, outputDir } = fixtureRoot();
  const { notePath } = writeArtifact({
    notesDir,
    artifactsDir,
    title: 'Source Note',
    body: '# Source Note\n\nSource notes remain authoritative.',
  });
  const before = fs.readFileSync(notePath, 'utf8');

  compileSecondbrainWiki({ artifactsDir, outputDir });

  assert.equal(fs.readFileSync(notePath, 'utf8'), before);
  assert.ok(fs.existsSync(path.join(outputDir, 'sources', 'source-note.md')));
});

test('compileSecondbrainWiki excludes private artifacts and knowledge units', () => {
  const { notesDir, artifactsDir, outputDir } = fixtureRoot();
  writeArtifact({
    notesDir,
    artifactsDir,
    title: 'Private Source',
    body: '# Private Source\n\nPrivate credential handling details should not be generated.',
  });
  const artifactPath = path.join(artifactsDir, 'private-source.json');
  const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
  artifact.privacyTier = 'private';
  artifact.knowledgeUnits = artifact.knowledgeUnits.map((unit) => ({
    ...unit,
    text: 'Private credential handling details should not be generated.',
    privacyDecision: {
      tier: 'private',
      excludedFromPromotion: true,
    },
  }));
  fs.writeFileSync(artifactPath, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');

  const result = compileSecondbrainWiki({ artifactsDir, outputDir });
  const index = fs.readFileSync(path.join(outputDir, 'index.md'), 'utf8');

  assert.equal(result.artifacts, 0);
  assert.doesNotMatch(index, /Private credential/);
  assert.equal(fs.existsSync(path.join(outputDir, 'sources', 'private-source.md')), false);
});

test('compileSecondbrainWiki removes stale generated pages before rebuilding', () => {
  const { notesDir, artifactsDir, outputDir } = fixtureRoot();
  const { artifactPath } = writeArtifact({
    notesDir,
    artifactsDir,
    title: 'Stale Source',
    body: '# Stale Source\n\nStale generated pages should disappear when source artifacts disappear.',
  });

  compileSecondbrainWiki({ artifactsDir, outputDir });
  assert.equal(fs.existsSync(path.join(outputDir, 'sources', 'stale-source.md')), true);

  fs.rmSync(artifactPath);
  const result = compileSecondbrainWiki({ artifactsDir, outputDir });

  assert.equal(result.artifacts, 0);
  assert.equal(fs.existsSync(path.join(outputDir, 'sources', 'stale-source.md')), false);
  assert.equal(fs.existsSync(path.join(outputDir, 'index.md')), true);
});

test('compileSecondbrainWiki refuses to reset unmanaged nonempty output directories', () => {
  const { notesDir, artifactsDir, outputDir } = fixtureRoot();
  writeArtifact({
    notesDir,
    artifactsDir,
    title: 'Unsafe Output',
    body: '# Unsafe Output\n\nThe build should not clean an unmanaged folder.',
  });
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(path.join(outputDir, 'manual.md'), '# Manual content\n', 'utf8');

  assert.throws(
    () => compileSecondbrainWiki({ artifactsDir, outputDir }),
    /Refusing to reset unmanaged generated wiki output directory/,
  );
  assert.equal(fs.readFileSync(path.join(outputDir, 'manual.md'), 'utf8'), '# Manual content\n');
});

test('resolveWikiBuildOptions defaults to visible wiki under configured vault', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'jarvos-wiki-config-'));
  const vaultDir = path.join(root, 'Vault');
  const configPath = path.join(root, 'jarvos.config.json');
  fs.writeFileSync(configPath, JSON.stringify({
    paths: {
      vault: vaultDir,
    },
  }));

  const options = resolveWikiBuildOptions({
    configPath,
    homeDir: root,
    env: {},
  });

  assert.equal(options.vaultDir, vaultDir);
  assert.equal(options.artifactsDir, path.join(vaultDir, '.jarvos', 'knowledge', 'artifacts'));
  assert.equal(options.outputDir, path.join(vaultDir, DEFAULT_WIKI_DIR_NAME));
});

test('resolveWikiBuildOptions expands tilde path overrides', () => {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'jarvos-wiki-home-'));
  const options = resolveWikiBuildOptions({
    homeDir: home,
    env: {
      JARVOS_VAULT_DIR: '~/Vault',
      JARVOS_KNOWLEDGE_ARTIFACTS_DIR: '~/Vault/.jarvos/knowledge/artifacts',
      JARVOS_GENERATED_WIKI_DIR: '~/Vault/Wiki',
    },
  });

  assert.equal(options.vaultDir, path.join(home, 'Vault'));
  assert.equal(options.artifactsDir, path.join(home, 'Vault', '.jarvos', 'knowledge', 'artifacts'));
  assert.equal(options.outputDir, path.join(home, 'Vault', 'Wiki'));
});

test('generated wiki CLI builds pages and prints json summary', () => {
  const { notesDir, artifactsDir, outputDir } = fixtureRoot();
  writeArtifact({
    notesDir,
    artifactsDir,
    title: 'CLI Build',
    body: '# CLI Build\n\nCLI builds should produce generated wiki pages.',
  });

  const cliPath = path.join(__dirname, '..', 'packages', 'jarvos-secondbrain-wiki', 'src', 'index.js');
  const result = spawnSync(process.execPath, [
    cliPath,
    '--artifacts-dir',
    artifactsDir,
    '--output-dir',
    outputDir,
    '--json',
  ], {
    encoding: 'utf8',
  });

  assert.equal(result.status, 0, result.stderr);
  const summary = JSON.parse(result.stdout);
  assert.equal(summary.artifacts, 1);
  assert.equal(summary.sourcePages, 1);
  assert.ok(fs.existsSync(path.join(outputDir, 'index.md')));
  assert.ok(fs.existsSync(path.join(outputDir, MANAGED_OUTPUT_MARKER)));
});
